# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaveTheFood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaveTheFood
	
  pod 'Alamofire'
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'SwiftyJSON'
  pod 'ChameleonFramework'

  target 'SaveTheFoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SaveTheFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
